### PR TITLE
nginx: Add worker_proccesses and worker_connections entries

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Adding these two entries improves benchmarking results upto 20% and
also reduces failed requests.

Signed-off-by: Lakshmipathi Ganapathi <lakshmi@supabase.io>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
```
m5a.4xlarge + 4 postgrest behind nginx LB 

GETSingle  (wo nginx optimization))
10, 0.00,7405.60117/s
50, 0.00,12595.870026/s
100, 0.00,12205.565782/s
150, 0.00,12208.238864/s

GETSingle 
10, 0.00,7434.346935/s
50, 0.00,16085.796612/s
100, 0.00,14986.371651/s
150, 0.00,14079.435378/s

POSTBulk (wo nginx optimization)
10, 0.00,2215.112789/s
50, 0.00,4569.790863/s
100, 100.00,11532.503857/s #failure
150, 100.00,11363.643744/s

POSTBulk
10, 0.00,2308.700058/s
50, 0.00,4917.483969/s
100, 0.00,5822.859096/s #no failure
150, 0.00,5244.821737/s

POSTSingle (wo nginx optimization)
10, 100.00,11529.260161/s
50, 100.00,11715.846538/s
100, 100.00,13589.886795/s
150, 100.00,13609.034938/s

POSTSingle
10, 0.00,3695.01501/s
50, 0.00,11643.947517/s
100, 0.02,13028.042333/s
150, 27.38,8720.762712/s
```

**Review by darora — APPROVED** [review]
Hmm this corrects our benchmarks; we already use these settings in production

**Comment by Lakshmipathi** [comment]
Running `m5a.4xlarge + 8 postgrest behind nginx LB (with nginx optimization)` gives slight read performance improvements for GETSingle but post call see decrease in results. So it seems better stick to `no.of postgrest == no.of core` in the system.

**Comment by Lakshmipathi** [comment]
Below, we can see nice improvements for `m5a.8xlarge + 8 postgrest behind nginx LB`  over previous `m5a.4xlarge + 4 postgrest behind nginx LB `  results.


```
m5a.8xlarge + 8 postgrest behind nginx LB 

GETSingle
10, 0.00,7481.717861/s
50, 0.00,23343.761169/s
100, 0.00,26567.056011/s
150, 0.02,26104.93628/s

POSTBulk(m5a.8xlarge)
10, 0.00,2265.263658/s
50, 0.00,5318.924262/s
100, 0.00,6617.157452/s
150, 0.00,7038.32145/s

POSTSingle(m5a.8xlarge)
10, 0.00,3943.897486/s
50, 0.00,13075.926288/s
100, 0.00,18033.74944/s
150, 0.00,18995.834173/s
```

**Pull request merged**
