### PR TITLE
postgrest: add comparison between pgbench and k6

### PR DESCRIPTION
**Pull request by steve-chavez**
Extracted the postgREST `GETSingle generated query from pg logs and run pgbench with it. This provides a comparison of the RPS and TPS between k6 and pgbench.

So the GETSingle generated query is proven to scale with bigger instances. However, I'm having an issue with scaling `GETSingle` through postgREST, on `m5a.8xlarge` I get worse numbers than on `m5a.4xlarge`.

I would like a couple more eyes here. Is my methodology wrong somehow? I'm testing pgbench with 10, 50 and 100 clients and k6 with 10, 50 and 100 VUs.

- [k6 GETSingle results rendered](https://github.com/steve-chavez/benchmarks/blob/pgbench-pgrst/postgrest/k6/results/K6_GET_SINGLE.txt)
  - [k6 GETSingle request](https://github.com/steve-chavez/benchmarks/blob/pgbench-pgrst/postgrest/k6/GETSingle.js)
- [pgbench GETSingle results rendered](https://github.com/steve-chavez/benchmarks/blob/pgbench-pgrst/postgrest/pgbench/results/PGBENCH_GET_SINGLE.txt)
  - [GETSingle query](https://github.com/steve-chavez/benchmarks/blob/pgbench-pgrst/postgrest/pgbench/GETSingle.sql)
---

If my methodology is not wrong, then I need to figure out what's wrong in postgREST(maybe it's not detecting the number of cores correctly).

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
hmm,strange. I can also confirm that `m5x.8xlarge` gets  worse numbers than on `m5x.4xlarge`. Also verified `m5x.12xlarge` also gave similar results like ``m5x.8xlarge`.

**Comment by steve-chavez** [comment]
As mentioned in https://github.com/PostgREST/postgrest/issues/2294#issuecomment-1138018595, I patched postgREST with a [new pool library](https://github.com/steve-chavez/postgrest/tree/scrive-pool) and ran the bench tests again. TLDR: the `m5a.8xlarge` numbers improve(coming from `m5a.4xlarge`) but they drop again on `m5a.12xlarge` and `m5a.16xlarge`.

|version |instance   |VUs|RPS          |
|--------|-----------|---|-------------|
|9.0.0   |m5a.4xlarge|100|4617.947865/s|
|new-pool|m5a.4xlarge|100|4338.542661/s|
|9.0.0   |m5a.8xlarge|100|3481.089877/s|
|new-pool|m5a.8xlarge|100|5131.852034/s|
|9.0.0   |m5a.12xlarge|100|2686.402242/s|
|new-pool|m5a.12xlarge|100|4580.536358/s|
|9.0.0   |m5a.16xlarge|100|2144.077842/s|
|new-pool|m5a.16xlarge|100|3762.884233/s|


Full results: [new-pool k6 GETSingle results rendered](https://github.com/steve-chavez/benchmarks/blob/61cc089bade8df08b915ca9721d904424b4750ca/postgrest/k6/results/NEW_POOL_K6_GET_SINGLE.txt)

**Comment by steve-chavez** [comment]
So I've been trying `pgbouncer` instead of the postgREST pool. For the low end `t3a.nano`:

<details>
 <summary>800.676889/s for 2 pgbouncers on the same pg instance</summary>
<pre>
    data_received..............: 7.6 MB 251 kB/s
    data_sent..................: 2.5 MB 82 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 24065
    http_req_blocked...........: avg=4.6µs   min=980ns   med=1.64µs  max=977.32µs p(90)=2.16µs  p(95)=2.6µs
    http_req_connecting........: avg=2.2µs   min=0s      med=0s      max=560.34µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=12.4ms  min=2.7ms   med=9.9ms   max=73.99ms  p(90)=23.61ms p(95)=28.51ms
    http_req_receiving.........: avg=36.52µs min=14.19µs med=35.28µs max=899.71µs p(90)=43.92µs p(95)=50.58µs
    http_req_sending...........: avg=9.37µs  min=6.04µs  med=8.23µs  max=416.24µs p(90)=10.49µs p(95)=12.5µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=12.35ms min=2.64ms  med=9.86ms  max=73.95ms  p(90)=23.56ms p(95)=28.47ms
    http_reqs..................: 24065  800.676889/s
    iteration_duration.........: avg=12.46ms min=2.76ms  med=9.96ms  max=74.04ms  p(90)=23.68ms p(95)=28.58ms
    iterations.................: 24065  800.676889/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

<details>
 <summary>1587.418643/s for postgREST + pgbouncer on the same instance, separate pg instance </summary>
<pre>
    data_received..............: 15 MB  498 kB/s
    data_sent..................: 4.9 MB 163 kB/s
  ✓ failed requests............: 0.00%  ✓ 0    ✗ 47701
    http_req_blocked...........: avg=4.5µs   min=980ns   med=1.64µs  max=965.88µs p(90)=2.25µs  p(95)=2.68µs
    http_req_connecting........: avg=2.16µs  min=0s      med=0s      max=932.75µs p(90)=0s      p(95)=0s
  ✓ http_req_duration..........: avg=6.22ms  min=2.26ms  med=5.66ms  max=25.12ms  p(90)=9.34ms  p(95)=10.92ms
    http_req_receiving.........: avg=36.18µs min=14.83µs med=35.15µs max=4.75ms   p(90)=43.73µs p(95)=49.19µs
    http_req_sending...........: avg=9.53µs  min=6.01µs  med=8.32µs  max=396.71µs p(90)=11µs    p(95)=12.88µs
    http_req_tls_handshaking...: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=6.17ms  min=2.22ms  med=5.61ms  max=25.08ms  p(90)=9.3ms   p(95)=10.87ms
    http_reqs..................: 47701  1587.418643/s
    iteration_duration.........: avg=6.28ms  min=2.31ms  med=5.72ms  max=25.67ms  p(90)=9.41ms  p(95)=10.98ms
    iterations.................: 47701  1587.418643/s
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
</pre>
</details>

Results are not looking good considering I get `2643.760356/s` for the postgREST pool.

pgbouncer consumes considerable CPU from what I've seen, I think that's mostly where the difference comes in the tests.

**Comment by steve-chavez** [comment]
So now I've been trying to tune GHC garbage collection. I got a hint from 
https://blog.noredink.com/post/666654908557180928/tuning-haskell-rts-for-kubernetes-part-2. By default, all cores participate in garbage collection, which is really wasteful, there's an [option](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--qn%20%E2%9F%A8x%E2%9F%A9) for limiting that to, say, 2 cores. When doing that I've been able to obtain noticeable better results while consuming half of the CPU that was used before this change.

[Full results of tuned GC](https://github.com/supabase/benchmarks/blob/4a3e749d245c5f3c9cc37821fbd8a9dab3ef22c1/postgrest/k6/results/TUNED_RTS_NEW_POOL_K6_GET_SINGLE.txt).

For example, for 50 VUs on the `m5a.4xlarge` I obtained `8417.12599/s` - the previous result was `5329.314248/s`.

**Comment by steve-chavez** [comment]
The good news with the above is that now the numbers for the load tests are maintained for the higher end instances `m5a.8xlarge`, `m5a.12xlarge`, `m5a.16xlarge`.

They still don't improve, but they do not drop like before.

**Comment by steve-chavez** [comment]
Made a [PR](https://github.com/PostgREST/postgrest/pull/2298) with the above fix and also a new [pre-release](https://github.com/PostgREST/postgrest/releases/tag/v9.0.0.20220531). With those I updated the bench tests results here.

(included POSTSingle and POSTBulk as well)

I think this should be good to merge now.

**Review by Lakshmipathi — APPROVED** [review]

**Pull request merged**
